import React, { useState } from 'react';
import { base44 } from '@/api/base44Client';
import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import { Loader2, Sparkles, TrendingUp, Lightbulb, RefreshCw, Repeat2 } from 'lucide-react';
import { toast } from 'sonner';
import IdeaCard from '@/components/idealab/IdeaCard';
import RepurposePanel from '@/components/idealab/RepurposePanel';
import { CEO_CONTEXT } from '@/lib/ceo-context';

const STRATEGY_OPTIONS = [
  { value: 'targeted_role', label: 'Targeted Role' },
  { value: 'storytelling', label: 'Storytelling' },
  { value: 'urgency', label: 'Urgency' },
  { value: 'social_proof', label: 'Social Proof' },
  { value: 'niche_community', label: 'Niche Community' },
  { value: 'carousel_text', label: 'Carousel Text' },
];

export default function IdeaLab() {
  const [ideas, setIdeas] = useState([]);
  const [isGenerating, setIsGenerating] = useState(false);
  const [savedIds, setSavedIds] = useState(new Set());
  const queryClient = useQueryClient();

  const { data: posts = [] } = useQuery({
    queryKey: ['generated-posts'],
    queryFn: () => base44.entities.GeneratedPost.list('-impressions', 50),
  });

  // Top performers: posts with meaningful engagement
  const topPosts = posts
    .filter(p => p.status === 'published' && (p.impressions > 0 || p.referrals > 0))
    .sort((a, b) => (b.impressions + b.referrals * 100) - (a.impressions + a.referrals * 100))
    .slice(0, 10);

  const saveMutation = useMutation({
    mutationFn: (idea) => base44.entities.GeneratedPost.create({
      title: idea.title,
      content: idea.content,
      strategy: idea.strategy,
      status: 'draft',
      notes: `Generated by IdeaLab. Structure: ${idea.structure}`,
    }),
    onSuccess: (post, idea) => {
      setSavedIds(prev => new Set([...prev, idea._id]));
      queryClient.invalidateQueries({ queryKey: ['generated-posts'] });
      toast.success(`"${post.title}" saved as draft!`);
    },
  });

  const handleGenerate = async () => {
    if (topPosts.length === 0) {
      toast.error('No published posts with engagement data found. Publish some posts and track metrics first.');
      return;
    }

    setIsGenerating(true);
    setIdeas([]);
    setSavedIds(new Set());

    // Build a summary of top performers for the LLM
    const topSummary = topPosts.map(p => ({
      title: p.title,
      strategy: p.strategy,
      impressions: p.impressions || 0,
      referrals: p.referrals || 0,
      hired: p.hired || 0,
      notes: p.notes || '',
    }));

    const strategyPerf = STRATEGY_OPTIONS.map(s => {
      const stratPosts = topPosts.filter(p => p.strategy === s.value);
      const avgImpressions = stratPosts.length
        ? Math.round(stratPosts.reduce((sum, p) => sum + (p.impressions || 0), 0) / stratPosts.length)
        : 0;
      return { strategy: s.label, posts: stratPosts.length, avgImpressions };
    }).filter(s => s.posts > 0);

    const prompt = `${CEO_CONTEXT}

You are an expert LinkedIn content strategist for a professional recruiter at micro1 (an AI recruitment platform). 
The CEO context above is optional background — use it only when it naturally adds depth or credibility to an idea. Not every idea needs to reference it.
Analyze the performance data from their top LinkedIn posts and generate 5 fresh content ideas that are likely to outperform based on patterns in the data.

TOP PERFORMING POSTS DATA:
${JSON.stringify(topSummary, null, 2)}

STRATEGY PERFORMANCE SUMMARY:
${JSON.stringify(strategyPerf, null, 2)}

Based on what worked best (high impressions, referrals, hires), generate 5 new content ideas.

Return a JSON object with this exact structure:
{
  "insights": "2-3 sentence summary of what patterns you identified in the data",
  "ideas": [
    {
      "title": "Short descriptive title for this post idea (max 10 words)",
      "strategy": "one of: targeted_role | storytelling | urgency | social_proof | niche_community | carousel_text",
      "reasoning": "1 sentence: why this idea should perform well based on the data",
      "structure": "Bullet-point outline of the post structure (4-6 lines)",
      "content": "Full draft of the LinkedIn post content, ready to use or edit. Follow the usual format: headline with 📍, referral link, personal intro, who should apply, roles list, closing, hashtags."
    }
  ]
}

The content field should contain a full, publish-ready draft of the post.
Target audience: experienced professionals in tech, design, science, media, finance, or management.
Referral link to always use: https://refer.micro1.ai/referral/jobs?referralCode=eaa2768a-4116-40a1-b897-971506bb359e`;

    const result = await base44.integrations.Core.InvokeLLM({
      prompt,
      response_json_schema: {
        type: 'object',
        properties: {
          insights: { type: 'string' },
          ideas: {
            type: 'array',
            items: {
              type: 'object',
              properties: {
                title: { type: 'string' },
                strategy: { type: 'string' },
                reasoning: { type: 'string' },
                structure: { type: 'string' },
                content: { type: 'string' },
              },
            },
          },
        },
      },
    });

    // Add a local _id for tracking saves
    const ideasWithId = (result.ideas || []).map((idea, i) => ({ ...idea, _id: `idea-${i}` }));
    setIdeas(ideasWithId);
    if (result.insights) {
      setInsights(result.insights);
    }
    setIsGenerating(false);
  };

  const [insights, setInsights] = useState('');
  const [tab, setTab] = useState('ideas');

  return (
    <div className="space-y-6">
      <div className="flex items-start justify-between">
        <div>
          <h1 className="text-2xl font-bold tracking-tight flex items-center gap-2">
            <Lightbulb className="w-6 h-6 text-yellow-500" />
            Idea Lab
          </h1>
          <p className="text-sm text-muted-foreground mt-1">
            AI-generated content ideas based on your top-performing posts
          </p>
        </div>
        {tab === 'ideas' && (
          <Button onClick={handleGenerate} disabled={isGenerating} className="gap-2 h-10">
            {isGenerating ? (
              <><Loader2 className="w-4 h-4 animate-spin" /> Analyzing…</>
            ) : ideas.length > 0 ? (
              <><RefreshCw className="w-4 h-4" /> Regenerate Ideas</>
            ) : (
              <><Sparkles className="w-4 h-4" /> Generate Ideas</>
            )}
          </Button>
        )}
      </div>

      {/* Tab switcher */}
      <div className="flex gap-1 p-1 bg-muted rounded-lg w-fit">
        <button
          onClick={() => setTab('ideas')}
          className={`flex items-center gap-1.5 px-4 py-1.5 rounded-md text-sm font-medium transition-all ${
            tab === 'ideas' ? 'bg-background shadow text-foreground' : 'text-muted-foreground hover:text-foreground'
          }`}
        >
          <Sparkles className="w-3.5 h-3.5" /> Idea Generator
        </button>
        <button
          onClick={() => setTab('repurpose')}
          className={`flex items-center gap-1.5 px-4 py-1.5 rounded-md text-sm font-medium transition-all ${
            tab === 'repurpose' ? 'bg-background shadow text-foreground' : 'text-muted-foreground hover:text-foreground'
          }`}
        >
          <Repeat2 className="w-3.5 h-3.5" /> Repurpose Post
        </button>
      </div>

      {tab === 'repurpose' ? (
        <RepurposePanel topPosts={topPosts} />
      ) : (
        <>
          {/* Data source summary */}
          <div className="flex items-center gap-3 p-3 rounded-lg bg-muted/40 border text-sm">
            <TrendingUp className="w-4 h-4 text-primary flex-shrink-0" />
            <span className="text-muted-foreground">
              Analyzing <span className="font-semibold text-foreground">{topPosts.length}</span> published posts with engagement data
              {topPosts.length === 0 && <span className="text-amber-600 ml-2">— publish posts and log metrics to unlock ideas</span>}
            </span>
          </div>

          {/* AI Insights banner */}
          {insights && (
            <div className="p-4 rounded-xl border border-primary/20 bg-primary/5">
              <p className="text-xs font-semibold text-primary uppercase tracking-wide mb-1">What the data says</p>
              <p className="text-sm text-foreground/80">{insights}</p>
            </div>
          )}

          {/* Loading skeleton */}
          {isGenerating && (
            <div className="grid md:grid-cols-2 xl:grid-cols-3 gap-4">
              {[1, 2, 3, 4, 5].map(i => (
                <div key={i} className="rounded-xl border bg-card p-5 space-y-3 animate-pulse">
                  <div className="h-4 bg-muted rounded w-3/4" />
                  <div className="h-3 bg-muted rounded w-1/3" />
                  <div className="h-3 bg-muted rounded w-full" />
                  <div className="h-3 bg-muted rounded w-5/6" />
                  <div className="h-20 bg-muted rounded" />
                </div>
              ))}
            </div>
          )}

          {/* Ideas grid */}
          {!isGenerating && ideas.length > 0 && (
            <div className="grid md:grid-cols-2 xl:grid-cols-3 gap-4">
              {ideas.map((idea) => (
                <IdeaCard
                  key={idea._id}
                  idea={idea}
                  saved={savedIds.has(idea._id)}
                  isSaving={saveMutation.isPending}
                  onSave={() => saveMutation.mutate(idea)}
                />
              ))}
            </div>
          )}

          {/* Empty state */}
          {!isGenerating && ideas.length === 0 && (
            <div className="flex flex-col items-center justify-center py-24 text-center space-y-4">
              <div className="w-16 h-16 rounded-2xl bg-yellow-50 flex items-center justify-center">
                <Lightbulb className="w-8 h-8 text-yellow-400" />
              </div>
              <div>
                <p className="font-semibold text-lg">No ideas yet</p>
                <p className="text-sm text-muted-foreground mt-1 max-w-sm">
                  Click "Generate Ideas" to let the AI analyze your best posts and suggest what to write next.
                </p>
              </div>
            </div>
          )}
        </>
      )}
    </div>
  );
}